settings:
  default-health: 100 #default health of new created necron stone
  default-respawn-after: 120 #broken necron stone will regenerate after 120 seconds
  default-reward-commands:
    - 'give %player% diamond 1' #give a diamond to player
  block-type-after-destroy: 'IRON_BLOCK' #block type after necron stone broken

hologram-active:
  height: 1.5
  lines:
    - 'Break the stone!'
    - ' '
    - 'Health: %health%/%max_health%'
    - 'Last damager: %last_damager%'

hologram-cooldown:
  height: 1.5
  lines:
    - 'Stone is regenerating!'
    - ' '
    - 'Remain: %<timePattern=HH:mm:ss>%'

messages:
  info-destroy-stone-broadcast: '%player% broke the stone at %location%!'
  info-respawn-stone-broadcast: 'stone at %location% respawned!'
  info-break-stone-actionbar: 'You broke the stone and its health is %health%/%max_health%'
